### ISSUE TITLE
same issue multiple time `runtime error`

### ISSUE THREAD

**Issue by khanjanny** [GhostTroops/scan4all#153]
Basic Scan

scan4all -l ips.txt -csv -o out.csv

after running portscan it throwing this error.

error log:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xe8f50f]

goroutine 138842775 [running]:
github.com/hktalent/scan4all/lib/util.(*CheckerTools).Check(0x0, {0xc01f1f0d40, 0x2, 0x2})
	/home/khan/Desktop/tools/scan4all/lib/util/checkerImp.go:80 +0x2f
github.com/hktalent/scan4all/lib/util.CheckResp({0xc00d57d980, 0x25}, {0xc00b391928, 0x1, 0x7f42d04d7310?})
	/home/khan/Desktop/tools/scan4all/lib/util/checkerImp.go:120 +0x54
github.com/hktalent/scan4all/lib/util.GetLimitReader(0xc00ae61b90)
	/home/khan/Desktop/tools/scan4all/lib/util/util.go:192 +0x55
github.com/hktalent/scan4all/lib/util.GetResponse.func1(0xc00ae61b90, {0x0?, 0x0?}, {0xc?, 0xc011bd3290?})
	/home/khan/Desktop/tools/scan4all/lib/util/util.go:214 +0x1ed
github.com/hktalent/PipelineHttp.(*PipelineHttp).DoGetWithClient4SetHd(0xc00a1cabb0, 0x0?, {0xc011bd3290, 0x25}, {0x20e96f5, 0x3}, {0x584d3c0, 0xc02a4cec00}, 0xc00b391ca8, 0xc00b391cd0, ...)
	/home/khan/Desktop/tools/scan4all/vendor/github.com/hktalent/PipelineHttp/PipelineHttp.go:277 +0xa1c
github.com/hktalent/scan4all/lib/util.GetResponse({0x0, 0x0}, {0x0, 0x0}, {0xc011bd3290, 0x25}, {0x20e96f5, 0x3}, {0x0, 0x0}, ...)
	/home/khan/Desktop/tools/scan4all/lib/util/util.go:205 +0x294
github.com/hktalent/scan4all/lib/util.HttpRequset({0xc011bd3290, 0x25}, {0x20e96f5?, 0x1?}, {0x0?, 0x1da5e40?}, 0xa5?, 0x7f42c89b6618?)
	/home/khan/Desktop/tools/scan4all/lib/util/util.go:244 +0x65
github.com/hktalent/scan4all/lib/util.TestIsWeb01({0xc00b50588a, 0x19})
	/home/khan/Desktop/tools/scan4all/lib/util/config.go:489 +0x3a5
github.com/hktalent/scan4all/lib/util.TestIsWeb(0xc00086e730)
	/home/khan/Desktop/tools/scan4all/lib/util/util.go:254 +0xad
github.com/hktalent/scan4all/webScan.CheckUrls(0x0?)
	/home/khan/Desktop/tools/scan4all/webScan/webScanUrls.go:46 +0x9e
github.com/hktalent/scan4all/pkg/naabu/v2/pkg/runner.(*Runner).Httpxrun.func1.1()
	/home/khan/Desktop/tools/scan4all/pkg/naabu/v2/pkg/runner/runner.go:91 +0x25
github.com/hktalent/scan4all/lib/util.DoSyncFunc.func1()
	/home/khan/Desktop/tools/scan4all/lib/util/Const.go:79 +0xe9
created by github.com/hktalent/scan4all/lib/util.DoSyncFunc
	/home/khan/Desktop/tools/scan4all/lib/util/Const.go:71 +0x6a
```

**Comment by ahisec** [comment]
我也遇到了一样的错误
